package collections.domain.model

data class CoinDetails(
    val id: String,
    val userId: String,
    val obverseUrl: String,
    val reverseUrl: String,
    val coinData: CoinData,
    val aiAnalysis: AiAnalysis,
    val catalogueNumbers: List<CatalogueNumber>,
    val setId: String?,
    val catalogCoinId: String?,
    val notes: String?,
    val createdAt: Long
) {
    data class CoinData(
        val countryOrIssuer: String?,
        val denomination: String?,
        val seriesName: String?,
        val year: Int?,
        val era: String?,
        val mintMark: String?,
        val metalComposition: String?,
        val weightGrams: Double?,
        val diameterMm: Double?,
        val thicknessMm: Double?,
        val edge: String?,
        val obverseDescription: String?,
        val reverseDescription: String?,
        val historicalContext: String?,
        val obverseLettering: String?,
        val reverseLettering: String?,
        val designerObverse: String?,
        val designerReverse: String?,
        val mintage: Long?,
        val shape: String?,
        val technique: String?,
        val orientation: String?,
        val mintName: String?,
        val ruler: String?,
        val objectType: String?,
        val demonetized: Boolean?,
        val tags: List<String>?,
        val numistaUrl: String?,
        val obverseThumbnailUrl: String?,
        val reverseThumbnailUrl: String?,
        val minYear: Int?,
        val maxYear: Int?
    )

    data class AiAnalysis(
        val overallConfidence: String?,
        val confidenceCountry: String?,
        val confidenceDenomination: String?,
        val confidenceSeries: String?,
        val confidenceYear: String?,
        val confidenceEra: String?,
        val mintMarkStatus: String?,
        val mintMarkConfidence: String?,
        val gradeName: String?,
        val gradeAbbreviation: String?,
        val gradeNumeric: Int?,
        val gradeConfidence: String?,
        val rarityQualitative: String?,
        val rarityScore: Double?,
        val valueLow: Double?,
        val valueHigh: Double?,
        val valueCurrency: String?,
        val positiveFeatures: List<String>?,
        val negativeFeatures: List<String>?,
        val supplySummary: String?,
        val demandSummary: String?,
        val valueDisclaimer: String?,
        val analysisNotes: String?,
        val obverseVisible: Boolean?,
        val reverseVisible: Boolean?,
        val imageFocus: String?,
        val imageLighting: String?,
        val imageResolution: String?,
        val imageCropping: String?,
        val imageIssues: List<String>?,
        val rawJson: String?
    )

    companion object {
        val dummyCoin = CoinDetails(
            id = "b584c85a-22cd-449b-a085-e22281a7eb6e",
            userId = "7553f609-b197-49a9-8159-4e269744d2be",
            obverseUrl = "https://d3gfqgm5ck0wic.cloudfront.net/users/7553f609-b197-49a9-8159-4e269744d2be/2244862f-80e5-4157-a699-2bde2f451e2a/125ad721-4a01-4d50-a34f-a62a9af82738-1",
            reverseUrl = "https://d3gfqgm5ck0wic.cloudfront.net/users/7553f609-b197-49a9-8159-4e269744d2be/2244862f-80e5-4157-a699-2bde2f451e2a/884dadd6-5d3b-4ff4-8cc4-55c30c3a7b6e-2",
            coinData = CoinData(
                countryOrIssuer = "greece",
                denomination = "1 euro",
                seriesName = "1 Euro (Greek National Side)",
                year = 2010,
                era = "Eurozone",
                mintMark = "anthemion",
                metalComposition = "Bimetallic: copper-nickel clad nickel centre in nickel brass ring",
                weightGrams = 7.5,
                diameterMm = 23.25,
                thicknessMm = 2.33,
                edge = "Segmented reeding",
                obverseDescription = "A reproduction of an antique tetradrachma (showing an owl) from Athens about 490 BC. is accompanied with the face value and encircled by the twelve stars of Europe",
                reverseDescription = "A map of Western Europe, next to the face value, shows the European continent without borders",
                historicalContext = "<p>The coin is issued in bankrolls and the below mint sets.</p>",
                obverseLettering = "1 ΕΥΡΩ ΓΣ 2009",
                reverseLettering = "1 EURO LL",
                designerObverse = "Geórgios Stamatópoulos",
                designerReverse = "Luc Luycx",
                mintage = 10000000,
                shape = "Round",
                technique = "Milled",
                orientation = "medal",
                mintName = "National Mint of the Bank of Greece",
                ruler = null,
                objectType = "Standard circulation coins",
                demonetized = false,
                tags = listOf("Bird", "Coin depiction", "Map", "Mythology"),
                numistaUrl = "https://en.numista.com/6352",
                obverseThumbnailUrl = "https://en.numista.com/catalogue/photos/grece/6054c27f23fff3.53135578-180.jpg",
                reverseThumbnailUrl = "https://en.numista.com/catalogue/photos/grece/6054c27f5e0f87.84669312-180.jpg",
                minYear = 2007,
                maxYear = 2026
            ),
            aiAnalysis = AiAnalysis(
                overallConfidence = "HIGH",
                confidenceCountry = "high",
                confidenceDenomination = "high",
                confidenceSeries = "high",
                confidenceYear = "high",
                confidenceEra = "high",
                mintMarkStatus = "visible",
                mintMarkConfidence = "high",
                gradeName = "Very Fine",
                gradeAbbreviation = "VF",
                gradeNumeric = 20,
                gradeConfidence = "medium",
                rarityQualitative = "Very Common",
                rarityScore = 0.1,
                valueLow = 1.0,
                valueHigh = 1.2,
                valueCurrency = "EUR",
                positiveFeatures = listOf(
                    "Clear date and mintmark",
                    "Strong central owl design details",
                    "Legends fully readable"
                ),
                negativeFeatures = listOf(
                    "Scratches and light scuffs on both sides",
                    "Tarnishing and minor circulation wear in fields"
                ),
                supplySummary = "Extremely abundant in circulation throughout the Eurozone.",
                demandSummary = "Low collector premium due to high mintage, though often saved by tourists and casual collectors for its distinctive historical design.",
                valueDisclaimer = "Value is highly dependent on wear and market conditions. For common circulating coins, the retail value is generally close to face value.",
                analysisNotes = "A circulating 1 Euro coin from Greece, dated 2010. The national reverse features the famous ancient Athenian owl design.",
                obverseVisible = true,
                reverseVisible = true,
                imageFocus = "high",
                imageLighting = "high",
                imageResolution = "high",
                imageCropping = "high",
                imageIssues = emptyList(),
                rawJson = null
            ),
            catalogueNumbers = listOf(
                CatalogueNumber(
                    catalogueName = "KM",
                    number = "214",
                    confidence = "HIGH"
                ),
                CatalogueNumber(
                    catalogueName = "Schön",
                    number = "174",
                    confidence = "HIGH"
                )
            ),
            setId = null,
            catalogCoinId = "e2ff0e72-64bb-4b7b-a6f8-3da4618a2146",
            notes = "A circulating 1 Euro coin from Greece, dated 2010. The national reverse features the famous ancient Athenian owl design.",
            createdAt = 1782131506175
        )
    }
}
